### PR TITLE
Introduce standard log fields and replace zap with logrus

### PR DESCRIPTION
**Pull request by kmjayadeep**
To introduce standard logging fields and conventions, we need to fix the following limitations with the current codebase

* `go-logr` logr.logger interface doesn't support log levels (they use verbose level number instead). 
* With zap implementation of go-logr, we managed to add support for `debug` loglevel, but `warn` is missing
* Top level fields (ts, msg etc) are not as per google structured logging standard. This makes it difficult to view the logs in google console. https://cloud.google.com/logging/docs/structured-logging
* If we use zap directly, we will have to change entire codebase to use the new methods from zap
* logr.Logger interface is currently in use everywhere (even inside controller-runtime). So our only option is to use a logger which is an implementation of this interface.

To fix this, this PR introduces the following changes (more PRs to follow)

* Replace zap with logrus. It is easier to migrate to logrus syntax in the current codebase than zap. See the difference below for the basic usage.
```go
# logrus
log.WithFields("slice","green").Info("something")

# zap
log.Info("something", zap.string("slice", "green"))
```
* Change log field names
  * level -> severity
  * msg -> message
  * ts -> timestamp
* Added `logrusr` package to convert logrus to logr implementation (will replace with our own implementation in next PRs)
* go fmt and go.mod changes

Next steps

* Replace logrusr with our own implementation to support the log levels (https://github.com/bombsimon/logrusr/blob/main/logrusr.go)
* Export log levels as constants and replace code blocks like below
```
log.V(1).Info("App pod is not part of the slice", "pod", pod.Name, "slice", slice.Name)
log.V(logger.DEBUG).Info("App pod is not part of the slice", "pod", pod.Name, "slice", slice.Name)

log.V(2).Info("App pod is not part of the slice", "pod", pod.Name, "slice", slice.Name)
log.V(logger.WARN).Info("App pod is not part of the slice", "pod", pod.Name, "slice", slice.Name)
```
* Improve log messages and fields

### CODE REVIEW

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2022-11-13T08:51:04-master-235/index.html'

**Comment by gourishkb** [comment]
HI @kmjayadeep , this is a great description. Thank you. 
I am not clear about the following, 

> Replace logrusr with our own implementation to support the log levels (https://github.com/bombsimon/logrusr/blob/main/logrusr.go) 
and 
> Export log levels as constants and replace code blocks like below
seem like the same steps to me or did I misunderstand you ?

The changes look good to me :+1:

**Review by gourishkb — APPROVED** [review]

**Review by rahulsawra98 — APPROVED** [review]
Great ! Thank you @kmjayadeep . LGTM

**Comment by kmjayadeep** [comment]
thanks @gourishkb. I'm closing this PR. I found that it is easy to implement this with zap itself, without needing to maintain our own implementation of logr.Logger. I will raise a separate PR

**Review by pnavali — COMMENTED** [review]
@kmjayadeep please add cluster-name and namespace to payload format.

**Pull request closed without merging**
