### PR TITLE
fix: reconcile gateway client's node port

### LINKED ISSUE #309: Reconcile port numbers in ovpn client deployments
### 📜 Description

An ovpn client deployment for a slice gateway is created with the NodePort port numbers specified in the workerslicegateway object. The logic to handle a change in the port numbers seems to be missing. The ovpn clients continue to connect on the previously specified port numbers. The ovpn client deployment needs to be updated to effect a change in the port number. 

### 👟 Reproduction steps

There are two options:
1. Delete the slice object manually on the designated server cluster. This will lead to deletion of the slicegateway objects as well. Make sure the NodePort services are also deleted. Then restart the worker-operator pod. This will lead to re-creation of the slice and slicegateway objects, and new NodePort services. The workerslicegateway objects are updated with new port numbers, but on the client cluster the port number is not updated in the ovpn deployment.

2. Manually edit the client deployment and update the port number to a random value. The worker-operator does not reconcile the deployment back to valid port numbers.  

### 👍 Expected behavior

The worker-operator on the client cluster should reconcile the ovpn deployments to use currently relevant port numbers.

### 👎 Actual Behavior

The ovpn client deployments continue to use invalid port numbers leading to loss in connectivity between clusters.

### 🐚 Relevant log output

_No response_

### Version

_No response_

### 🖥️ What operating system are you seeing the problem on?

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kon3m**
# Description

Fixes #309 
## How Has This Been Tested?
Tested it manually using two single node kind clusters.

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have ran `go fmt`
* [ ] I have updated the helm chart as required by this PR.
* [ ] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit test cases.
* [ ] I have verified the E2E test cases with new code changes.
* [ ] I have added all the required E2E test cases.

## Does this PR introduce a breaking change?

```release-note

```

### CODE REVIEW

**Review by Rahul-D78 — APPROVED** [review]
LGTM :+1:

**Comment by kon3m** [comment]
@narmidm could you please review and approve this PR? this is a duplicate of [333](https://github.com/kubeslice/worker-operator/pull/333). I have opened a new one as multiple authors/files got added to the previous PR while rebasing and fixing conflicts which are not relevant to the PR, so opened this new clean one.

**Comment by narmidm** [comment]
Sure @kon3m, will review it and update you soon.

**Review by narmidm — APPROVED** [review]

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2024-04-04T18:04:41-master-463/index.html'

**Comment by narmidm** [comment]
> @narmidm a lot of e2e tests seem to fail after the recent update made to the pipeline.

We've identified the root cause of the end-to-end failure; it was due to the last release. Please allow me half an hour to release a new image for automation, after which I will rerun and verify your PR. 

Apologies for the delayed response.

**Comment by narmidm** [comment]
@kon3m can you sync your Branch with master once.

**Comment by mridulgain** [comment]
@kon3m A fix has been added for the PR pipeline failure. Pls re sync your branch.

**Comment by mridulgain** [comment]
@kon3m We have added a small fix for the PR pipeline failure. Please re sync once more..

**Comment by kon3m** [comment]
@mridulgain @narmidm i have just updated it, can you please trigger the e2e pipeline?

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2024-04-15T17:03:02-master-468/index.html'

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2024-04-15T20:08:08-master-469/index.html'

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2024-04-16T06:16:45-master-469/index.html'

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2024-04-16T10:14:23-master-470/index.html'

**Pull request merged**
