### PR TITLE
fix(ServiceExport): Reject Conflicting Alias Names for ServiceExport object (#315)

### LINKED ISSUE #315: Reject conflicting alias names for exported services
### 📜 Description

A service can be exported over the slice network by creating a ServiceExport object. Such services are accessible through the slice fqdn: <name-of-the-service>.<namespace-name>.svc.slice.local. But the users can choose to use a different fqdn by adding alias names to the ServiceExport object. Currently, there is no validation of the alias names. We cannot have conflicting alias names in the sense that the user should not be allowed to set the same alias name different services. 

### 👟 Reproduction steps

Export two services by creating ServiceExport objects. Set the same alias names on both the ServiceExport objects. 

The dns resolution of the exported service names will point to incorrect addresses. Service S1 resolution could result in endpoint IP addresses belonging to Service S2. 

### 👍 Expected behavior

The alias names need to be validated and admission of ServiceExport objects with conflicting alias names should be rejected. 

### 👎 Actual Behavior

ServiceExport objects for different services but with same alias names are allowed to be created.

### 🐚 Relevant log output

_No response_

### Version

_No response_

### 🖥️ What operating system are you seeing the problem on?

_No response_

### ✅ Proposed Solution

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by soharab-ic**
# Description
 The validating webhook will validate the ServiceExport object and admission of ServiceExport objects with conflicting alias names will be rejected.

Fixes #315 

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have ran `go fmt`
* [ ] I have updated the helm chart as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [x] I have added all the required unit test cases.
* [ ] I have verified the E2E test cases with new code changes.
* [ ] I have added all the required E2E test cases.

## Does this PR introduce a breaking change?

```release-note

```

### CODE REVIEW

**Comment by soharab-ic** [comment]
The issue https://github.com/kubeslice/worker-operator/pull/339 impacts this PR. Hence holding this until it is resolved.

**Comment by narmidm** [comment]
> The issue #338 impacts this PR. Hence holding this until it is resolved.

https://github.com/kubeslice/worker-operator/pull/339
https://github.com/kubeslice/worker-operator/issues/338

the issue is closed, and fix is merged to master please proceed @soharab-ic

**Comment by narmidm** [comment]
@soharab-ic, can you rebase with the latest master. it has some fixes of E2E pipeline. It will help run E2E when PR will be ready.

**Comment by soharab-ic** [comment]
> @soharab-ic, can you rebase with the latest master. it has some fixes of E2E pipeline. It will help run E2E when PR will be ready.

Sure @narmidm

**Comment by soharab-ic** [comment]
@bharath-avesha @narmidm Please review this PR.

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2024-03-19T05:22:38-master-442/index.html'

**Comment by soharab-ic** [comment]
@narmidm Fixed the build failure issue.
E2E is failing because of this
```
"Error: INSTALLATION FAILED: failed to fetch https://raw.githubusercontent.com/kubeslice/dev-charts/gh-pages/nexus/kubeslice-controller-1.2.1.tgz : 404 Not Found",`
```

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2024-03-19T12:24:40-master-443/index.html'

**Comment by narmidm** [comment]
@soharab-ic ,A release has recently occurred; could you please resolve the conflict on the branch?

**Comment by soharab-ic** [comment]
> @soharab-ic ,A release has recently occurred; could you please resolve the conflict on the branch?

Sure @narmidm

**Comment by soharab-ic** [comment]
@narmidm Resolved conflicts, Please trigger E2E pipeline.

**Comment by soharab-ic** [comment]
@narmidm @bharath-avesha Any update on the E2E pipeline?

**Comment by narmidm** [comment]
> @narmidm @bharath-avesha Any update on the E2E pipeline?

Fixed & started the pipeline.

**Comment by mridulgain** [comment]
@soharab-ic a fix has been added for the e2e pipeline workflow. Please sync your branch.

**Comment by soharab-ic** [comment]
> @soharab-ic a fix has been added for the e2e pipeline workflow. Please sync your branch.

Synced my branch.
Thanks @mridulgain

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2024-04-17T07:32:56-master-471/index.html'

**Comment by soharab-ic** [comment]
@narmidm @mridulgain I see three end-to-end tests are failing. Is the e2e pipeline have some issues?
I have not added any e2e tests.

**Review by mridulgain — APPROVED** [review]
Lgtm!
In the latest test report https://github.com/kubeslice/worker-operator/pull/337#issuecomment-2060583849, a sufficient number of tests from the Worker and SliceHealth suites have passed to ensure that existing functionalities are unaffected. Notably, the iperf tests, which include ServiceExport creation to make the service available across clusters connected under the Slice, have also passed successfully.

**Review by Rahul-D78 — APPROVED** [review]

**Comment by soharab-ic** [comment]
Thanks everyone.

**Pull request merged**
