### PR TITLE
fix(): fixed slicegw health status for single cluster (#207)

### PR DESCRIPTION
**Pull request by gourishkb**
* fix(): fixed slicegw health status for single cluster

* fix(): fixed broken UTs

* fix(): fixed ITs

* fix(): handling multiple slicegw deployments

---------

### CODE REVIEW

**Comment by gourishkb** [comment]
https://github.com/kubeslice/worker-operator/pull/207 PR for reference

**Comment by gourishkb** [comment]
Allure report for https://github.com/kubeslice/worker-operator/pull/207 PR  https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2023-04-01T16:48:11-release-guwahati-394/index.html

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2023-04-02T17:35:45-master-395/index.html'

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2023-04-02T20:13:18-master-396/index.html'

**Comment by NishantSingh10** [comment]
report link  'https://kubeslice.github.io/e2e-allure-reports/Kind-worker-operator-2023-04-02T20:58:08-master-396/index.html'

**Pull request closed without merging**
